layout_spectrum: 1
typography_spectrum: 0.2825568
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.05832867
  brandColors:
    - '#D3DEE4'
    - '#544735'
    - '#786C56'
    - '#191A1E'
    - '#B0BBB7'
  rhythmicContrast: 0.9982079
name: Slice of life
