name: Slice of life
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2825568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D3DEE4'
    - '#544735'
    - '#786C56'
    - '#191A1E'
    - '#B0BBB7'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.9982079
purpose: []
